# Generated by Django 3.0.4 on 2020-03-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ticket_priority',
            field=models.CharField(choices=[('P4', 'Priority 4'), ('P3', 'Priority 3'), ('P2', 'Priority 2'), ('P1', 'Priority 1')], default='P4', max_length=2),
        ),
    ]
