# Generated by Django 3.0.4 on 2020-03-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200328_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ticket_priority',
            field=models.CharField(choices=[('Priority 4', 'Priority 4'), ('Priority 3', 'Priority 3'), ('Priority 2', 'Priority 2'), ('Priority 1', 'Priority 1')], default='Priority 4', max_length=10),
        ),
    ]
