# Generated by Django 3.0.4 on 2020-03-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200328_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Waiting internal', 'Waiting internal'), ('Waiting on vendor', 'Waiting on vendor'), ('Closed', 'Closed')], default='In Progress', max_length=50),
        ),
    ]
