# Generated by Django 3.0.4 on 2020-04-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200401_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='priority',
            field=models.CharField(choices=[('4 - Low', '4 - Low'), ('3 - Averege', '3 - Averege'), ('2 - High', '2 - High'), ('1 - Critical', '1 - Critical')], default='4 - Low', max_length=20),
        ),
    ]
